class AppRoutesNames {
  // static const String kLanguage = "/";
  static const String kCart = "/cart";
  static const String kHome = "/";
  static const String kText = "/test";
  static const String kSettings = "/settings";
  static const String kItems = "/items";
  static const String kLogin = '/login';
  static const String kSignUp = "/signUp";
  static const String kCheckout = "/checkout";
  static const String kTestData = "/testData";
  static const String kAddressAdd = "/addressAdd";
  static const String kOnBoarding = "/onBoarding";
  static const String kCheckEmail = "/checkEmail";
  static const String kAddressEdit = "/addressEdit";
  static const String kAddressView = "/addressView";
  static const String kItemsDetails = "/itemsDetails";
  static const String kNotification = "/notification";
  static const String kOrdersDetails = "/ordersDetails";
  static const String kResetPassword = "/resetPassword";
  static const String kSuccessSignUp = "/successSignUp";
  static const String kOrdersArchieve = "/ordersArchieve";
  static const String kForgetPassword = "/forgetPassword";
  static const String kVerifyCodeSignUp = "/verifyCodeSignUp";
  static const String kAddressAddDetails = "/addressAddPartTwo";
  static const String kSuccessCheckEmail = "/successCheckEmail";
  static const String kSuccessResetPassword = "/successResetPassword";
  static const String kForgetPasswordVerifyCode = "/forgetPasswordVerifyCode";
}
